### ISSUE TITLE
Whenever used with express it throws "Error: Can't set headers after they are sent."

### ISSUE THREAD

**Issue by ishandutta2007** [kljensen/node-sse-example#3]

**Comment by kljensen** [comment]
That happens in an express app when you try to write to the after it has
been closed.

Sincerely,
Kyle

**Comment by ishandutta2007** [comment]
I have made it work by using res.write() followed by res.end().
I was under the impression res.send() would do the same but seems like res.send() isn't sending anything to the client. However I would have liked to send response without having to call res.end() as I understand that beats the basic tenet of SSE

**Comment by ishandutta2007** [comment]
In express app for your code changing

``` javascript
        clients[clientId].write("data: "+ msg + "\n\n"); // <- Push a message to a single attached client
```

to

``` javascript
        clients[clientId].end("data: "+ msg + "\n\n"); // <- Push a message to a single attached client
```

works keeping everything else same. However it keeps creating new clientIds for subsequent messages.

**Comment by kljensen** [comment]
Thanks, can you submit a pull request?
