### ISSUE TITLE
clients grows

### ISSUE THREAD

**Issue by gaxolio** [kljensen/node-sse-example#5]
Hi. Thanks for your example.
I put your code in my app and it is working well.
I am able to send alerts to all clients connected.
Only one problem. After a client subscribe, it is added to an object array.
It seems, that my clients after a while, they call again(subscribe) the server and they are added again into object array.
Therefore my clients{} array grows continuously.
This happens also if I don't interact with application. No click.
Is not clear for me why clients re-subcribe.
How can I check if a client is a 'new' client or it is already subscribed?
This is no a really issue of your code but perhaps this problem can be mentioned in your example.
Thanks for support.
Sergio

**Comment by titan83** [comment]
@gaxolio , hello.
I have the same problem as you. Did you solve it?
Thanks.

**Comment by gaxolio** [comment]
@titan83 , unfortunately no.

**Comment by kljensen** [comment]
Friends - you should use client side cookies (or localstorage) to store a unique, per-client session id. You can then use this to ensure each client is connected only a single time in the event of a disconnection/re-connection cycle.
